### ISSUE TITLE
generator-openerp-addon : Install isue

### ISSUE THREAD

**Issue by diassynthesis** [head-js/nerv#1]
Getting the following error (npm install -g generator-openerp-addon):
--- npm-debug.log ---0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'https://github.com/shuaishuai/generator-openerp-addon' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose cache add [ 'https://github.com/shuaishuai/generator-openerp-addon',
4 verbose cache add   null ]
5 verbose cache add name=undefined spec="https://github.com/shuaishuai/generator-openerp-addon" args=["https://github.com/shuaishuai/generator-openerp-addon",null]
6 verbose parsed url { protocol: 'https:',
6 verbose parsed url   slashes: true,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: 'github.com',
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: 'github.com',
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: '/shuaishuai/generator-openerp-addon',
6 verbose parsed url   path: '/shuaishuai/generator-openerp-addon',
6 verbose parsed url   href: 'https://github.com/shuaishuai/generator-openerp-addon' }
7 silly lockFile 59094920-uaishuai-generator-openerp-addon https://github.com/shuaishuai/generator-openerp-addon
8 verbose lock https://github.com/shuaishuai/generator-openerp-addon /home/openerp/.npm/59094920-uaishuai-generator-openerp-addon.lock
9 verbose addRemoteTarball [ 'https://github.com/shuaishuai/generator-openerp-addon',
9 verbose addRemoteTarball   null ]
10 info retry fetch attempt 1 at 11:20:48
11 verbose fetch to= /home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon
12 http GET https://github.com/shuaishuai/generator-openerp-addon
13 http 200 https://github.com/shuaishuai/generator-openerp-addon
14 verbose tar unpack /home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon
15 silly lockFile 5dce8c12-i-generator-openerp-addon-unpack tar:///home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon-unpack
16 verbose lock tar:///home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon-unpack /home/openerp/.npm/5dce8c12-i-generator-openerp-addon-unpack.lock
17 silly lockFile 1132e67d-uaishuai-generator-openerp-addon tar:///home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon
18 verbose lock tar:///home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon /home/openerp/.npm/1132e67d-uaishuai-generator-openerp-addon.lock
19 silly gunzTarPerm modes [ '755', '644' ]
20 error not a package /home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon
21 silly lockFile 5dce8c12-i-generator-openerp-addon-unpack tar:///home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon-unpack
22 silly lockFile 5dce8c12-i-generator-openerp-addon-unpack tar:///home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon-unpack
23 silly lockFile 1132e67d-uaishuai-generator-openerp-addon tar:///home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon
24 silly lockFile 1132e67d-uaishuai-generator-openerp-addon tar:///home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon
25 silly lockFile 59094920-uaishuai-generator-openerp-addon https://github.com/shuaishuai/generator-openerp-addon
26 silly lockFile 59094920-uaishuai-generator-openerp-addon https://github.com/shuaishuai/generator-openerp-addon
27 error Error: ENOENT, open '/home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon-unpack/package.json'
28 error If you need help, you may report this _entire_ log,
28 error including the npm and node versions, at:
28 error     http://github.com/npm/npm/issues
29 error System Linux 3.8.0-44-generic
30 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "https://github.com/shuaishuai/generator-openerp-addon"
31 error cwd /home/openerp
32 error node -v v0.10.29
33 error npm -v 1.4.14
34 error path /home/openerp/tmp/npm-6618-97GjXQjB/github.com/shuaishuai/generator-openerp-addon-unpack/package.json
35 error code ENOENT
36 error errno 34
37 verbose exit [ 34, true ]
--- End Log ---
The folder is created but with no package.jspn inside it, just index.js file in it.

**Comment by hbrls** [comment]
This is a startup project and I've not yet published it to `npm`. You can not install it by `npm install`.

However, you can clone this git repo to your computer. And then

```
$ cd /path/to/generator-openerp-addon
$ npm link
```

Then you can run `yo openerp-addon` anywhere.
